import json
import multiprocessing
import numpy as np
import pandas as pd
import sys
import time
from utility_constants import *
from utility_dataframes import move_columns_next_to_each_other_in_dataframe, write_dataframe_to_fwf
from utility_functions import *
from utility_e3sm_netcdf import *

def extract_dataframe_rows_for_given_year(df, year):
    """ 
    Processes the Pandas DataFrame so that it contains only the rows pertaining to the given year, where the year (or 'time') is a DataFrame index.

    Parameters:
        df: DataFrame of interest.
        year: Year of interest.

    Returns:
        DataFrame containing only the rows for the given year, with the 'time' column dropped.
    """
    # Select rows where time equals year, keeping the spatial index.
    df_year = df.xs(year, level='time')
    return df_year

def extract_netcdf_file_into_dataframe_single_year(ds, areas, variables, region, year):
    """ 
    For the given year, extracts the specified variables from the E3SM human component (EHC) land surface data file into a Pandas DataFrame. 

    Parameters:
        ds: xarray Dataset for the NetCDF file generated by the EHC during run time. It contains data on land surface variables like harvest 
        and grazing. 
        areas: Grid cell areas.
        variables: List of variables we want to extract from the NetCDF file. 
        region: String for the region of interest. If not specified or not recognized, then there will be no restrictions on the lat/lon coordinates. 
        year: Year of interest.

    Returns:
        DataFrame containing one column for each of the variables, plus a column for the specific year of interest.
    """
    # Make a local copy to avoid modifying the shared list.
    variables = variables.copy()
    
    # If grazing or harvest are of interest, make sure to also extract the land fractions for vegetation and the plant-functional types (PFTs).
    if 'GRAZING' in variables or any('HARVEST_' in variable for variable in variables):
        if 'PCT_NAT_PFT' not in variables:
            variables.append('PCT_NAT_PFT')
        if 'PCT_NATVEG' not in variables:
            variables.append('PCT_NATVEG')        

    # Convert the Dataset to create an overall DataFrame that stores all variables except those for land fractions and PFTs. 
    # Create a second DataFrame to store the land fractions and PFTs. 
    variables_except_pfts = variables.copy()
    variables_pfts = []
    if 'PCT_NAT_PFT' in variables:
        variables_except_pfts.remove('PCT_NAT_PFT')
        variables_pfts.append('PCT_NAT_PFT')
    if variables_except_pfts:
        df = ds[variables_except_pfts].to_dataframe()
        # Reduce the DataFrame to only the rows for the specific year of interest.
        df = extract_dataframe_rows_for_given_year(df, year)
    if variables_pfts:
        df_pfts = ds[variables_pfts].to_dataframe()
        df_pfts = extract_dataframe_rows_for_given_year(df_pfts, year)
        
    # Ensure df exists even if only PFT variables were requested.
    if not variables_except_pfts:
        # Create empty DataFrame with the correct spatial index from df_pfts.
        if variables_pfts:
            df = pd.DataFrame(index=df_pfts.index.droplevel('natpft').unique())
        else:
            raise ValueError('No variables requested!')

    # Divide the vegetation percent by 100 to change it to a fraction and update the label accordingly.
    if 'PCT_NATVEG' in variables:
        df['PCT_NATVEG'] = df['PCT_NATVEG'].fillna(0)/100
        df = df.rename(columns={'PCT_NATVEG': 'FRAC_VEG'})
        
        # SAFETY: Validate FRAC_VEG is a valid fraction.
        if (df['FRAC_VEG'] < -0.001).any() or (df['FRAC_VEG'] > 1.001).any():
            print(f'ERROR in year {year}: FRAC_VEG outside [0,1] range!')
            print(f'  min: {df["FRAC_VEG"].min():.6f}, max: {df["FRAC_VEG"].max():.6f}')
            raise ValueError(f'Invalid FRAC_VEG values in year {year}')
        
    # Add a column for the area at each lat/lon coordinate to the overall DataFrame.
    df['AREA (km^2)'] = areas
    
    # SAFETY: Validate grid cell areas
    if (areas < 0).any():
        print(f'ERROR in year {year}: Negative areas detected!')
        raise ValueError(f'Negative grid cell areas in year {year}')
    
    if df['AREA (km^2)'].max() > 1e8:  # Earth's largest grid cell ~100,000 km²
        print(f'ERROR in year {year}: Unreasonably large areas!')
        print(f'  Max area: {df["AREA (km^2)"].max():.2e} km² (Earth surface = 5.1e8 km²)')
        raise ValueError(f'Invalid areas in year {year}')

    # 17 PFTs in order: 1 bare, 8 tree, 3 shrub, 3 grass, 1 crop, 1 empty. These can be further subgrouped as follows:
    # Bare soil (index 0), forest (the 8 trees, indices 1--8); shrub (indices 9--11); grass (indices 12--14), crop (index 15). Ignore the empty PFT.
    if 'PCT_NAT_PFT' in variables:
        
        df_pfts = df_pfts.reset_index(level='natpft')
        
        # Get data for the individual PFTs (again ignoring the empty one), as well as the aggregate subgroups.
        pft_labels = [f'PFT_{i}_AREA (km^2)' for i in range(16)]
        pft_labels.extend(['BARE_AREA (km^2)', 'FOREST_AREA (km^2)', 'SHRUB_AREA (km^2)', 'GRASS_AREA (km^2)', 'CROP_AREA (km^2)'])
        pft_min_max_indices = [(i, i) for i in range(16)]
        pft_min_max_indices.extend([(0, 0), (1, 8), (9, 11), (12, 14), (15, 15)])
        
        # Select only the rows that pertain to this particular PFT category and for each lat/lon coordinate, sum over all PFTS if a subgroup.
        for index, pft_label in enumerate(pft_labels):
            pft_min_index, pft_max_index = pft_min_max_indices[index][0], pft_min_max_indices[index][1]
            df_this_pft = df_pfts[(df_pfts['natpft'] >= pft_min_index) & (df_pfts['natpft'] <= pft_max_index)]
            # Add up the percentages over all PFTs in the subgroup and divide that total percent by 100 to change it to a fraction.
            df_this_pft = df_this_pft['PCT_NAT_PFT'].groupby(['lsmlat', 'lsmlon']).sum().fillna(0)/100
            # Add a column to the overall DataFrame to record the area of this PFT category (individual or subgroup) at each lat/lon coordinate.
            df[pft_label] = df['AREA (km^2)'] * df['FRAC_VEG'] * df_this_pft     
            
        # SAFETY: Validate PFT areas are reasonable.
        pft_area_cols = [col for col in df.columns if 'AREA (km^2)' in col and 'PFT' in col]
        for col in pft_area_cols:
            if (df[col] < 0).any():
                print(f'ERROR in year {year}: Negative {col} detected!')
                raise ValueError(f'Negative PFT area in year {year}')
            max_val = df[col].max()
            if max_val > 1e8:  # No PFT area should exceed max grid cell
                print(f'ERROR in year {year}: {col} too large: {max_val:.2e} km²')
                raise ValueError(f'Invalid PFT area in year {year}')

    # Convert the grazing and harvest variables from a unitless fraction into an area by multiplying with the area of the PFT aggregate subgroup.
    grazing_harvest_variables = ['GRAZING', 'HARVEST_SH1', 'HARVEST_SH2', 'HARVEST_SH3', 'HARVEST_VH1', 'HARVEST_VH2']
    pft_area_columns = ['GRASS_AREA (km^2)', 'FOREST_AREA (km^2)', 'FOREST_AREA (km^2)', 'FOREST_AREA (km^2)', 'FOREST_AREA (km^2)', 
                          'FOREST_AREA (km^2)']
    for index in range(len(grazing_harvest_variables)):
        grazing_harvest_variable = grazing_harvest_variables[index]
        # Only process this variable if it was actually requested and exists in the DataFrame.
        if grazing_harvest_variable in df.columns:
            df[grazing_harvest_variable] = df[grazing_harvest_variable]*df[pft_area_columns[index]]
            df = df.rename(columns={grazing_harvest_variable: grazing_harvest_variable + '_AREA (km^2)'})
    
    # Create another column for the total harvest, which is the sum of all the harvest variables present in the DataFrame.
    harvest_variables = ['HARVEST_SH1_AREA (km^2)', 'HARVEST_SH2_AREA (km^2)', 'HARVEST_SH3_AREA (km^2)', 'HARVEST_VH1_AREA (km^2)', 
                         'HARVEST_VH2_AREA (km^2)']
    harvest_variables = [x for x in harvest_variables if x in df.columns]
    if harvest_variables:
        df['HARVEST_AREA (km^2)'] = df[harvest_variables].sum(axis=1)
        df = move_columns_next_to_each_other_in_dataframe(df, harvest_variables[len(harvest_variables)-1], 'HARVEST_AREA (km^2)')
    
    # Sum over all latitude/longitude coordinates to get an area-weighted sum for each variable.
    if 'FRAC_VEG' in df.columns:
        df['FRAC_VEG'] *= df['AREA (km^2)']
    
    # SAFETY: Check for inf/NaN before summing.
    if df.isin([np.inf, -np.inf]).any().any():
        inf_cols = df.columns[df.isin([np.inf, -np.inf]).any()].tolist()
        print(f'ERROR in year {year}: Infinite values in columns: {inf_cols}')
        raise ValueError(f'Infinite values detected in year {year}')
    
    df = df.sum(skipna=True).to_frame().T

    # Vegetation fraction should be an area-weighted mean, and not an area-weighted sum, so we should divide its sum by the total area.
    if 'FRAC_VEG' in df.columns:
        df['FRAC_VEG'] /= np.sum(areas)

    # Add year column.
    column_names_with_year_first = ['Year']
    column_names_with_year_first.extend(df.columns)
    df['Year'] = year
    
    # SAFETY: Final validation of output (allow tiny floating-point errors).
    if (df.select_dtypes(include=[np.number]) < -0.001).any().any():
        numeric_cols = df.select_dtypes(include=[np.number]).columns
        neg_cols = [col for col in numeric_cols if (df[col] < -0.001).any()]
        print(f'ERROR in year {year}: Negative values in final output: {neg_cols}')
        raise ValueError(f'Negative values in final output for year {year}')
    
    return df[column_names_with_year_first]

def extract_time_series_from_netcdf_file(inputs):
    """ 
    Extracts the specified variables from an E3SM-generated NetCDF file into a Pandas DataFrame and performs the indicated operation on the variables.
    This NetCDF file is generated dynamically during run time by the E3SM human component (EHC) and contains land surface data like harvest, grazing. 

    Parameters:
        inputs: Dictionary containing the user choice inputs for different options, such as the variables that they want to extract from the file. 

    Returns:
        DataFrame containing one column for each of the variables, plus a column for the year.
    """
    # Start timing for this file.
    file_start_time = time.time()
    
    # Extract all user selections, some being supplied with default choices. Calculate the total number of years. Set the path and name of the file.
    simulation_path = inputs['simulation_path']
    output_file = inputs['output_file']
    variables = inputs['variables']
    region = inputs.get('region', None)
    write_to_csv = inputs.get('write_to_csv', False)
    start_year = inputs.get('start_year', 2015)
    end_year = inputs.get('end_year', 2100)
    max_processes = inputs.get('max_processes', MAX_PROCESSES)
    file = os.path.join(simulation_path, 'surfdata_iESM_dyn.nc')
    
    # Verify the output file is writable before doing any processing, so a bad path or permissions problem surfaces immediately.
    try:
        open(output_file, 'a').close()
    except OSError as e:
        print(f"Error: cannot write to output file '{output_file}': {e}")
        return

    # Load file. Do it in this function (outside of the multiprocessing steps) so that the file is loaded only once.
    # Prefilter to only load variables that are needed: the user-requested variables, those that may be added implicitly
    # for grazing/harvest calculations, and the auxiliary variables required for area/fraction calculations.
    # This reduces memory usage and I/O time by avoiding loading unnecessary variables from the file.
    print(f"Loading {file}...")
    auxiliary_vars = ['AREA', 'LANDFRAC_PFT', 'PFTDATA_MASK']
    implicit_vars = ['PCT_NAT_PFT', 'PCT_NATVEG']
    vars_to_retain = set(variables) | set(auxiliary_vars) | set(implicit_vars)
    all_vars_in_file = list(xr.open_dataset(file, decode_times=False).data_vars)
    drop_vars = [v for v in all_vars_in_file if v not in vars_to_retain]
    ds = xr.open_dataset(file, drop_variables=drop_vars)
    # Drop duplicate 'time' coordinate values (e.g., that get generated during restarts), keeping the data that correspond to the last occurrence.
    ds = ds.drop_duplicates(dim='time', keep='last') 
    
    # Calculate grid cell areas, with regional filtering if needed
    print("Calculating grid cell areas...")
    areas, ds, _, _ = find_gridcell_areas_in_netcdf_file_ds(ds, region=region, file_type='surfdata_iESM_dyn')
    
    # Check that all requested variables exist in the dataset before doing any per-year processing.
    missing_vars = [v for v in variables if v not in ds.data_vars
                    and v not in ('PCT_NAT_PFT', 'PCT_NATVEG')]  # these may be added implicitly
    if missing_vars:
        print(f"Error: the following variables were not found in {file}: {missing_vars}")
        print(f"  Available variables: {list(ds.data_vars)}")
        ds.close()
        return
    print(f"Variables to extract ({len(variables)}): {variables}")

    # Check which years actually exist in the file.
    print(f'Checking available years in {file}...')
    if 'YEAR' in ds:
        available_years = sorted([int(y) for y in ds['YEAR'].values])
    else:
        available_years = sorted([int(y) for y in ds['time'].values])

    years_to_process = [y for y in available_years if start_year <= y <= end_year]

    if len(years_to_process) == 0:
        print(f'WARNING: No years in range {start_year}-{end_year} found in file!')
        return
    
    num_years = len(years_to_process)

    # Use multiprocessing to extract data from the file for each individual year. 
    # Put the data from each year into DataFrame and store all such DataFrames in a list.
    # TODO: Currently multiprocessing is not working properly, so processing sequentially instead.
    '''
    arguments = list(zip([ds]*num_years, [areas]*num_years, [variables]*num_years, 
                     [region]*num_years, years_to_process))
    num_processes = min(MAX_PROCESSES, num_years)
    print(f'Processing {num_years} years with multiprocessing...')
    with multiprocessing.Pool(processes=num_processes) as pool:
        dataframes_for_each_year = list(pool.starmap(extract_netcdf_file_into_dataframe_single_year, arguments))
    ds.close()
    '''

    print(f"Processing {num_years} years sequentially...")
    dataframes_for_each_year = []
    for i, year in enumerate(years_to_process, 1):
        print(f" {file}: Processing year {year} [{i}/{num_years}]...")
        df = extract_netcdf_file_into_dataframe_single_year(ds, areas, variables, region, year)
        dataframes_for_each_year.append(df)

    # Concatenate all DataFrames in the list together to form a single DataFrame over all years. Sort by year.
    df = pd.concat(dataframes_for_each_year)
    df.sort_values(['Year'], inplace=True)

    # Check for missing years in the concatenated DataFrame and warn the user about any gaps.
    actual_years = set(df['Year'])
    missing_years = sorted(set(years_to_process) - actual_years)
    if missing_years:
        print(f"Warning: {len(missing_years)} missing years in output: {missing_years}")

    # Close the dataset now that all years have been processed.
    ds.close()

    # Write the DataFrame to the specified output file.
    if write_to_csv or output_file.endswith('.csv'):
        df.to_csv(output_file, index=False)
    else:
        write_dataframe_to_fwf(output_file, df)
    
    # Print elapsed time for this file.
    file_elapsed_time = time.time() - file_start_time
    print(f'Elapsed time for {output_file}: {file_elapsed_time:.2f} seconds')


###---------------Begin execution---------------###
if __name__ == '__main__':

    # Run this script together with the input JSON file(s) on the command line.
    start_time_total = time.time()
    if len(sys.argv) < 2:
        print('Usage: python e3sm_extract_time_series_surfdata_iesm_dyn.py `path/to/json/input/file(s)\'')
        sys.exit()

    # Read and load the JSON file(s) into a list of dictionaries. Each block in a JSON file represents one time series output file.
    list_of_inputs = []
    for index in range(1, len(sys.argv)):
        input_file = sys.argv[index]
        with open(input_file) as f:
            list_of_inputs.extend(json.load(f))

    # Process multiple files in parallel using multiprocessing.
    print(f"\nProcessing {len(list_of_inputs)} file(s)...")

    if len(list_of_inputs) == 1:
        # Single file: no need for multiprocessing.
        extract_time_series_from_netcdf_file(list_of_inputs[0])
    else:
        # Multiple files: process them in parallel.
        num_processes = min(MAX_PROCESSES, len(list_of_inputs))
        with multiprocessing.Pool(processes=num_processes) as pool:
            pool.map(extract_time_series_from_netcdf_file, list_of_inputs)
    
    # Print the total execution time needed to complete all data extraction operations.
    end_time = time.time()
    elapsed_time = end_time - start_time_total
    print(f"Elapsed time for extracting all time series data: {elapsed_time:.2f} seconds")
